import type { AudioTrack } from "./store"

export const mockTracks: AudioTrack[] = [
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "Luna Wave",
    coverUrl: "/placeholder.svg?height=300&width=300",
    audioUrl: "/audio/demo.mp3",
    duration: 245,
    price: 5.5,
    owned: false,
    description: "An ethereal journey through ambient soundscapes",
    category: "Electronic",
  },
  {
    id: "2",
    title: "Urban Pulse",
    artist: "Beat Maker Pro",
    coverUrl: "/placeholder.svg?height=300&width=300",
    audioUrl: "/audio/demo.mp3",
    duration: 180,
    price: 3.2,
    owned: true,
    description: "Hard-hitting beats for the streets",
    category: "Hip Hop",
  },
  {
    id: "3",
    title: "Acoustic Sessions Vol. 1",
    artist: "Sarah Morgan",
    coverUrl: "/placeholder.svg?height=300&width=300",
    audioUrl: "/audio/demo.mp3",
    duration: 320,
    price: 8.0,
    owned: false,
    description: "Intimate acoustic performances recorded live",
    category: "Acoustic",
  },
  {
    id: "4",
    title: "Tech Talk: AI Revolution",
    artist: "Future Podcast",
    coverUrl: "/placeholder.svg?height=300&width=300",
    audioUrl: "/audio/demo.mp3",
    duration: 1820,
    price: 2.5,
    owned: false,
    description: "Deep dive into artificial intelligence",
    category: "Podcast",
  },
  {
    id: "5",
    title: "Jazz After Dark",
    artist: "The Smooth Trio",
    coverUrl: "/placeholder.svg?height=300&width=300",
    audioUrl: "/audio/demo.mp3",
    duration: 280,
    price: 6.5,
    owned: true,
    description: "Smooth jazz for late night listening",
    category: "Jazz",
  },
  {
    id: "6",
    title: "EDM Festival Mix 2024",
    artist: "DJ Nexus",
    coverUrl: "/placeholder.svg?height=300&width=300",
    audioUrl: "/audio/demo.mp3",
    duration: 420,
    price: 4.8,
    owned: false,
    description: "High energy festival anthems",
    category: "EDM",
  },
]
